
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module Keyboard(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// Seg7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// PS2 //////////
	inout 		          		PS2_CLK,
	inout 		          		PS2_CLK2,
	inout 		          		PS2_DAT,
	inout 		          		PS2_DAT2
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

MyKeyboard(			.clk(CLOCK_50),
						.clrn(SW[0]),
						.ps2_clk(PS2_CLK),
						.ps2_data(PS2_DAT),
						//output reg [7:0] data,
						//output [7:0] ascii,
						.d_digit_low(HEX0),
						.d_digit_high(HEX1),
						.a_digit_low(HEX2),
						.a_digit_high(HEX3),
						.c_digit_low(HEX4),
						.c_digit_high(HEX5),
						//output reg[15:0] count,
						.ctrl(LEDR[0]),
						.shift(LEDR[1]),
						.up(LEDR[2]),
						.caps(LEDR[3])
						);


//=======================================================
//  Structural coding
//=======================================================



endmodule
